const express = require("express");
const controller = require("../controllers/discoveryController");
const router = express.Router();
router.get("/candidates", controller.list);
router.post("/run", controller.run);
router.patch("/candidates/:id/decision", controller.decide);
router.get("/work-intakes", controller.listWorkIntakes);
router.get("/candidates/:id/work-intake", controller.getWorkIntake);
router.post("/candidates/:id/work-intake/handoff", controller.prepareWorkIntakeHandoff);
router.post("/candidates/:id/work-intake/mission", controller.verifyWorkIntakeAndCreateMission);
router.post("/candidates/:id/execution-mission", controller.createExecutionMission);
router.get("/execution-missions", controller.listExecutionMissions);
router.post("/execution-missions/:id/prepare", controller.prepareExecutionMission);
router.post("/execution-missions/:id/decision", controller.decideExecutionMission);
router.get("/execution-missions/:id/decisions", controller.listExecutionMissionDecisions);
router.post("/execution-missions/:id/resubmit", controller.resubmitExecutionMission);
router.patch("/execution-missions/:id/tasks/:taskId", controller.transitionExecutionTask);
router.get("/execution-missions/:id/task-events", controller.listExecutionTaskEvents);
router.post("/execution-missions/:id/auto-run", controller.runExecutionTask);
router.post("/execution-missions/:id/auto-run-all", controller.runExecutionMissionToCompletion);
router.get("/execution-missions/:id/task-runs", controller.listExecutionTaskRuns);
router.post("/execution-missions/:id/action-requests", controller.createExternalActionRequest);
router.get("/execution-missions/:id/action-requests", controller.listExternalActionRequests);
router.post("/execution-missions/:id/action-requests/:requestId/decision", controller.decideExternalActionRequest);
router.get("/execution-missions/:id/action-requests/:requestId/decisions", controller.listExternalActionDecisions);
router.post("/execution-missions/:id/action-requests/:requestId/completion", controller.recordExternalActionCompletion);
router.get("/execution-missions/:id/mvp-readiness", controller.getMvpReadiness);
router.get("/connectors", controller.listRevenueConnectors);
router.post("/execution-missions/:id/action-requests/:requestId/dispatch", controller.dispatchExternalAction);
router.get("/execution-missions/:id/action-requests/:requestId/dispatches", controller.listConnectorDispatches);
router.get("/deployment-readiness", controller.getDeploymentReadiness);
router.post("/execution-missions/:id/action-requests/:requestId/verified-earning", controller.recordVerifiedEarning);
router.get("/execution-missions/:id/pilot-ledger", controller.listPilotLedger);
router.get("/payments/razorpay-test/readiness", controller.getRazorpayTestReadiness);
router.post("/payments/razorpay-test/links", controller.prepareRazorpayTestLink);
router.post("/payments/razorpay-test/webhook", controller.verifyRazorpayTestWebhook);
module.exports = router;
