const express = require("express");
const controller = require("../controllers/discoveryController");
const router = express.Router();
router.get("/candidates", controller.list);
router.post("/run", controller.run);
router.patch("/candidates/:id/decision", controller.decide);
router.post("/candidates/:id/execution-mission", controller.createExecutionMission);
router.get("/execution-missions", controller.listExecutionMissions);
router.post("/execution-missions/:id/prepare", controller.prepareExecutionMission);
router.post("/execution-missions/:id/decision", controller.decideExecutionMission);
router.get("/execution-missions/:id/decisions", controller.listExecutionMissionDecisions);
router.post("/execution-missions/:id/resubmit", controller.resubmitExecutionMission);
router.patch("/execution-missions/:id/tasks/:taskId", controller.transitionExecutionTask);
router.get("/execution-missions/:id/task-events", controller.listExecutionTaskEvents);
router.post("/execution-missions/:id/auto-run", controller.runExecutionTask);
router.get("/execution-missions/:id/task-runs", controller.listExecutionTaskRuns);
module.exports = router;
