/**
 * 🦅 GARUDA Event Nervous System — Standard Event Types
 * Phase 2 & Cross-Universe Integration
 * Central dictionary of all verified business, engineering, vertical, and intelligence events.
 * Enforces stable event naming and prevents rogue string proliferation.
 */

const GARUDA_EVENT_TYPES = Object.freeze({
  // Phase 1: Inbound & Commercial Acquisition
  LEAD_CAPTURED: "LEAD_CAPTURED",
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_QUALIFIED: "LEAD_QUALIFIED",
  LEAD_ATTRIBUTED: "LEAD_ATTRIBUTED",
  PROPOSAL_CREATED: "PROPOSAL_CREATED",
  PROPOSAL_SENT: "PROPOSAL_SENT",
  PROPOSAL_APPROVED: "PROPOSAL_APPROVED",
  PROPOSAL_ACCEPTED: "PROPOSAL_ACCEPTED",
  PAYMENT_ORDER_CREATED: "PAYMENT_ORDER_CREATED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  PROJECT_ACTIVATED: "PROJECT_ACTIVATED",

  // Phase 2: Governed Client Delivery Engine
  EXECUTION_PLANNED: "EXECUTION_PLANNED",
  EXECUTION_PENDING_WORKER: "EXECUTION_PENDING_WORKER",
  EXECUTION_RUNNING: "EXECUTION_RUNNING",
  TASK_COMPLETED: "TASK_COMPLETED",
  VALIDATION_STARTED: "VALIDATION_STARTED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DELIVERY_READY: "DELIVERY_READY",
  EXECUTION_FAILED: "EXECUTION_FAILED",

  // Phase 3 & Vertical: Real Estate Growth OS
  REAL_ESTATE_PROJECT_CREATED: "REAL_ESTATE_PROJECT_CREATED",
  REAL_ESTATE_LEAD_CAPTURED: "REAL_ESTATE_LEAD_CAPTURED",
  REAL_ESTATE_LEAD_DEDUPLICATED: "REAL_ESTATE_LEAD_DEDUPLICATED",
  REAL_ESTATE_LEAD_QUALIFIED: "REAL_ESTATE_LEAD_QUALIFIED",
  REAL_ESTATE_LEAD_SCORED: "REAL_ESTATE_LEAD_SCORED",
  SITE_VISIT_REQUESTED: "SITE_VISIT_REQUESTED",
  SITE_VISIT_BOOKED: "SITE_VISIT_BOOKED",
  SITE_VISIT_COMPLETED: "SITE_VISIT_COMPLETED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_ATTRIBUTED: "BOOKING_ATTRIBUTED",
  REVENUE_ATTRIBUTED: "REVENUE_ATTRIBUTED",
  LEAD_LOST: "LEAD_LOST",

  // Phase 4: Creative & Brand Universe
  CREATIVE_BRIEF_CREATED: "CREATIVE_BRIEF_CREATED",
  CREATIVE_CONCEPT_CREATED: "CREATIVE_CONCEPT_CREATED",
  CREATIVE_ASSET_REQUESTED: "CREATIVE_ASSET_REQUESTED",
  CREATIVE_ASSET_GENERATED: "CREATIVE_ASSET_GENERATED",
  CREATIVE_ASSET_FAILED: "CREATIVE_ASSET_FAILED",
  CREATIVE_ASSET_APPROVED: "CREATIVE_ASSET_APPROVED",
  CAMPAIGN_ASSET_READY: "CAMPAIGN_ASSET_READY",
  BRAND_PROFILE_CREATED: "BRAND_PROFILE_CREATED",
  BRAND_PROFILE_UPDATED: "BRAND_PROFILE_UPDATED",

  // Phase 7 & 8: Performance Marketing & Growth
  CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
  CAMPAIGN_UPDATED: "CAMPAIGN_UPDATED",
  CAMPAIGN_ACTIVE: "CAMPAIGN_ACTIVE",
  PERFORMANCE_SIGNAL_RECORDED: "PERFORMANCE_SIGNAL_RECORDED",

  // Phase 6: Agent Workforce & Orchestration
  AGENT_TASK_CREATED: "AGENT_TASK_CREATED",
  AGENT_TASK_STARTED: "AGENT_TASK_STARTED",
  AGENT_TASK_COMPLETED: "AGENT_TASK_COMPLETED",
  AGENT_TASK_FAILED: "AGENT_TASK_FAILED",
  HUMAN_HANDOFF_REQUIRED: "HUMAN_HANDOFF_REQUIRED",

  // Phase 5 & 9: Intelligence, Knowledge, & Learning
  KNOWLEDGE_SOURCE_UPDATED: "KNOWLEDGE_SOURCE_UPDATED",
  OUTCOME_RECORDED: "OUTCOME_RECORDED",
  LEARNING_SIGNAL_CAPTURED: "LEARNING_SIGNAL_CAPTURED",

  // Lifecycle Completion & Settlement
  CLIENT_DELIVERY_ACCEPTED: "CLIENT_DELIVERY_ACCEPTED",
  FINAL_PAYMENT_RECEIVED: "FINAL_PAYMENT_RECEIVED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",

  // System Failures & Observability
  SYSTEM_ERROR: "SYSTEM_ERROR"
});

const GARUDA_ENTITY_TYPES = Object.freeze({
  LEAD: "lead",
  PROPOSAL: "proposal",
  PAYMENT: "payment",
  PROJECT: "project",
  TASK: "task",
  DELIVERY: "delivery",
  SYSTEM: "system",
  REAL_ESTATE_PROJECT: "real_estate_project",
  REAL_ESTATE_LEAD: "real_estate_lead",
  SITE_VISIT: "site_visit",
  BOOKING: "booking",
  CREATIVE_BRIEF: "creative_brief",
  CREATIVE_ASSET: "creative_asset",
  BRAND_PROFILE: "brand_profile",
  MARKETING_CAMPAIGN: "marketing_campaign",
  CONVERSION_EVENT: "conversion_event",
  AGENT_TASK: "agent_task",
  LEARNING_SIGNAL: "learning_signal"
});

module.exports = {
  GARUDA_EVENT_TYPES,
  GARUDA_ENTITY_TYPES
};
