const crypto = require("crypto");
function fail(message, statusCode = 400) { throw Object.assign(new Error(message), { statusCode }); }
function hash(value) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
const CONNECTORS = Object.freeze({
  sandbox_handoff: Object.freeze({ id: "sandbox_handoff", name: "GARUDA Sandbox Handoff", enabled: true, production: false, supportedActions: ["outreach", "application", "contract", "delivery", "deployment"], requiresCredentials: false }),
  manual_receipt: Object.freeze({ id: "manual_receipt", name: "Founder Manual Receipt", enabled: true, production: false, supportedActions: ["payment_verification"], requiresCredentials: false }),
  signed_webhook: Object.freeze({ id: "signed_webhook", name: "GARUDA Signed Production Webhook", enabled: true, production: true, supportedActions: ["outreach", "application", "contract", "delivery", "deployment"], requiresCredentials: true })
});
function listConnectors() { const webhook = require("./revenueSignedWebhookService").configured(); return Object.values(CONNECTORS).map((item) => ({ ...item, operational: item.id === "signed_webhook" ? webhook.enabled : item.enabled, health: item.id === "signed_webhook" ? webhook : undefined })); }
function resolveConnector(id, actionType) { const connector = CONNECTORS[String(id || "")]; if (!connector || !connector.enabled) fail("Connector is not allow-listed", 404); if (!connector.supportedActions.includes(actionType)) fail(`Connector ${connector.id} does not support ${actionType}`, 409); return connector; }
function validateDispatch(request = {}, input = {}) {
  if (request.status !== "handoff_ready") fail("Connector dispatch requires an approved handoff-ready action", 409);
  if (!request.handoffPackage?.packageHash || !request.latestDecisionHash) fail("Connector dispatch requires handoff and decision hashes", 409);
  const connector = resolveConnector(input.connectorId, request.actionType); const mode = input.dryRun === false ? "dispatch" : "dry_run";
  if (mode === "dispatch" && connector.production !== true) fail("This connector supports dry-run validation only", 409);
  const payload = { connectorId: connector.id, mode, requestKey: request.requestKey, packageHash: request.handoffPackage.packageHash, decisionHash: request.latestDecisionHash, evidenceHash: request.evidenceHash, actionType: request.actionType, destination: request.destination };
  return { connector, mode, payload, requestHash: hash(payload), idempotencyKey: hash({ connectorId: connector.id, mode, requestKey: request.requestKey, packageHash: request.handoffPackage.packageHash }) };
}
function buildReceipt(validation, previousDispatchHash = null, now = new Date()) { const response = { accepted: true, simulated: validation.connector.production !== true, connectorId: validation.connector.id, providerReference: `${validation.connector.id}:${validation.requestHash.slice(0, 16)}`, validatedAt: new Date(now).toISOString() }; const record = { connectorId: validation.connector.id, mode: validation.mode, status: validation.mode === "dry_run" ? "validated" : "dispatched", idempotencyKey: validation.idempotencyKey, requestHash: validation.requestHash, response, previousDispatchHash, governance: { connectorAllowListed: true, actionDecisionBound: true, handoffHashBound: true, externalSideEffectPerformed: validation.mode === "dispatch", paymentClaimAllowed: false } }; return { ...record, receiptHash: hash(record) }; }
async function dispatch(actionRequestId, input = {}, context = {}) { const mongoose = require("mongoose"); const { founderApprovalGranted } = require("./revenueConversionService"); const { RevenueExternalActionRequest } = require("../models/RevenueExternalActionRequest"); const { RevenueConnectorDispatch } = require("../models/RevenueConnectorDispatch"); if (!founderApprovalGranted(context.founderApproved)) fail("Founder approval is required for connector dispatch", 403); if (!mongoose.Types.ObjectId.isValid(String(actionRequestId || ""))) fail("Invalid action request id"); const request = await RevenueExternalActionRequest.findById(actionRequestId); if (!request) fail("Action request not found", 404); const validation = validateDispatch(request.toObject(), input); const existing = await RevenueConnectorDispatch.findOne({ idempotencyKey: validation.idempotencyKey }); if (existing) return existing.toJSON(); const previous = await RevenueConnectorDispatch.findOne({ actionRequestId }).sort({ createdAt: -1 }).lean(); let receipt = buildReceipt(validation, previous?.receiptHash || null); if (validation.connector.id === "signed_webhook" && validation.mode === "dispatch") { const response = await require("./revenueSignedWebhookService").send(validation, context.webhook || {}); const record = { ...receipt, status: "dispatched", response, governance: { ...receipt.governance, externalSideEffectPerformed: true } }; receipt = { ...record, receiptHash: hash(record) }; } return (await RevenueConnectorDispatch.create({ missionId: request.missionId, actionRequestId: request._id, ...receipt })).toJSON(); }
async function listDispatches(actionRequestId) { const { RevenueConnectorDispatch } = require("../models/RevenueConnectorDispatch"); return (await RevenueConnectorDispatch.find({ actionRequestId }).sort({ createdAt: 1 })).map((item) => item.toJSON()); }
module.exports = { CONNECTORS, buildReceipt, dispatch, hash, listConnectors, listDispatches, resolveConnector, validateDispatch };
