const assert = require("assert"); const service = require("./revenueExternalActionService"); const readiness = require("./revenueMvpReadinessService");
const truthHash = "f".repeat(64);
const mission = { id: "m1", status: "founder_approved", missionHash: "m".repeat(64), realWorkIntake: { truthHash, workAuthorizationConfirmed: true, listingClassification: "public_listing_not_contract" }, opportunity: { engagementVerification: { verified: true, reference: "contract-001", workAuthorizationConfirmed: true, termsAcceptedByClient: true, truthHash } }, founderDecision: { decisionHash: "d".repeat(64) }, deliverableWorkspace: { status: "complete" }, workPackages: [{ id: "t1", status: "completed", evidence: [{ kind: "artifact", label: "Offer", reference: "workspace://offer", sha256: "a".repeat(64) }] }] };
const request = service.buildRequest(mission, { actionType: "delivery", summary: "Deliver verified package", destination: "founder-selected channel" }, new Date("2026-01-01"));
assert.strictEqual(request.status, "pending_founder"); assert.strictEqual(request.governance.externalExecutionAuthorized, false);
assert.throws(() => service.buildRequest({ ...mission, deliverableWorkspace: { status: "active" } }, { actionType: "delivery", summary: "x" }), /complete/);
const decision = service.buildDecision({ ...request, id: "r1" }, { decision: "approved" }, null, new Date("2026-01-02"));
const handoff = service.buildHandoff({ ...request, status: "handoff_ready", latestDecisionHash: decision.decisionHash }, new Date("2026-01-03")); assert.strictEqual(handoff.governance.externalExecutionPerformed, false);
assert.throws(() => service.buildCompletionReceipt({ ...request, status: "handoff_ready" }, { provider: "x", reference: "y", evidence: "z" }), /handoff/);
const receipt = service.buildCompletionReceipt({ ...request, status: "handoff_ready", handoffPackage: handoff }, { provider: "manual", reference: "receipt-1", evidence: "Founder verified" }); assert.ok(receipt.receiptHash);
const report = readiness.assessReadiness(mission, [{ ...request, status: "externally_completed", completionReceipt: receipt }]); assert.strictEqual(report.workingMvp, true); assert.strictEqual(report.revenueClaimAllowed, false);
console.log("External action approval, handoff, receipt, and MVP readiness validation passed.");
