const crypto = require("crypto");
const { ACTION_TYPES } = require("../models/RevenueExternalActionRequest");
function fail(message, statusCode = 400) { throw Object.assign(new Error(message), { statusCode }); }
function hash(value) { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function text(value, name, max = 1000, required = false) { const result = String(value || "").trim(); if (required && !result) fail(`${name} is required`); if (result.length > max) fail(`${name} exceeds ${max} characters`); return result; }
function missionObject(value) { return value && typeof value.toObject === "function" ? value.toObject() : value || {}; }
function assertMissionReady(missionInput) { const mission = missionObject(missionInput); if (mission.status !== "founder_approved") fail("External action requires a Founder-approved mission", 409); if (mission.deliverableWorkspace?.status !== "complete") fail("External action requires a complete deliverable workspace", 409); if (!(mission.workPackages || []).length || !(mission.workPackages || []).every((item) => item.status === "completed" && (item.evidence || []).length)) fail("External action requires evidence for every work package", 409); return mission; }
function buildRequest(missionInput, input = {}, now = new Date()) {
  const mission = assertMissionReady(missionInput); const actionType = text(input.actionType, "actionType", 40, true);
  if (!ACTION_TYPES.includes(actionType)) fail(`actionType must be one of: ${ACTION_TYPES.join(", ")}`);
  const deliverables = (mission.workPackages || []).flatMap((task) => (task.evidence || []).map((item) => ({ taskId: task.id, kind: item.kind, label: item.label, reference: item.reference, sha256: item.sha256 || null }))).slice(0, 50);
  const evidenceHash = hash({ missionHash: mission.missionHash, founderDecision: mission.founderDecision?.decisionHash, deliverables });
  const record = { missionId: String(mission._id || mission.id), actionType, summary: text(input.summary, "summary", 1000, true), destination: text(input.destination, "destination", 500), deliverables, evidenceHash, createdAt: new Date(now).toISOString() };
  return { ...record, requestKey: hash(record), status: "pending_founder", governance: { actionSpecificApprovalRequired: true, externalExecutionAuthorized: false, automaticSubmissionAllowed: false, paymentClaimAllowed: false } };
}
function buildDecision(requestInput, input = {}, previousDecisionHash = null, now = new Date()) {
  const request = missionObject(requestInput); if (request.status !== "pending_founder" && request.status !== "changes_required") fail("Action request is not awaiting Founder decision", 409);
  const decision = text(input.decision, "decision", 40, true).toLowerCase(); if (!["approved", "request_changes", "rejected"].includes(decision)) fail("Decision must be approved, request_changes, or rejected");
  const notes = text(input.notes, "notes", 2000, decision !== "approved");
  const payload = { missionId: String(request.missionId), actionRequestId: String(request._id || request.id), actionType: request.actionType, decision, notes, evidenceHash: request.evidenceHash, previousDecisionHash: previousDecisionHash || null, actor: "founder", decidedAt: new Date(now).toISOString(), governance: { authorizesOnlyPreparedHandoff: decision === "approved", automaticExternalExecution: false, paymentVerified: false } };
  return { ...payload, decisionHash: hash(payload) };
}
function buildHandoff(requestInput, now = new Date()) { const request = missionObject(requestInput); if (request.status !== "handoff_ready" || !request.latestDecisionHash) fail("Approved action-specific decision is required for handoff", 409); const payload = { requestKey: request.requestKey, actionType: request.actionType, summary: request.summary, destination: request.destination, deliverables: request.deliverables || [], evidenceHash: request.evidenceHash, decisionHash: request.latestDecisionHash, preparedAt: new Date(now).toISOString(), governance: { manualOrConnectorHandoffOnly: true, externalExecutionPerformed: false } }; return { ...payload, packageHash: hash(payload) }; }
function buildCompletionReceipt(requestInput, input = {}, now = new Date()) { const request = missionObject(requestInput); if (request.status !== "handoff_ready" || !request.handoffPackage?.packageHash) fail("Prepared handoff package is required", 409); const reference = text(input.reference, "reference", 500, true); const provider = text(input.provider, "provider", 160, true); const evidence = text(input.evidence, "evidence", 1000, true); const payload = { requestKey: request.requestKey, packageHash: request.handoffPackage.packageHash, reference, provider, evidence, completedAt: new Date(now).toISOString(), paymentVerified: request.actionType === "payment_verification" && input.paymentVerified === true, actor: "founder" }; return { ...payload, receiptHash: hash(payload) }; }
async function findMission(id) { const mongoose = require("mongoose"); const { RevenueExecutionMission } = require("../models/RevenueExecutionMission"); if (!mongoose.Types.ObjectId.isValid(String(id || ""))) fail("Invalid execution mission id"); const item = await RevenueExecutionMission.findById(id); if (!item) fail("Execution mission not found", 404); return item; }
async function createRequest(missionId, input = {}, context = {}) { const { founderApprovalGranted } = require("./revenueConversionService"); const { RevenueExternalActionRequest } = require("../models/RevenueExternalActionRequest"); if (!founderApprovalGranted(context.founderApproved)) fail("Founder approval is required to create an external action request", 403); const record = buildRequest(await findMission(missionId), input); const existing = await RevenueExternalActionRequest.findOne({ requestKey: record.requestKey }); if (existing) return existing.toJSON(); return (await RevenueExternalActionRequest.create(record)).toJSON(); }
async function listRequests(missionId) { const { RevenueExternalActionRequest } = require("../models/RevenueExternalActionRequest"); return (await RevenueExternalActionRequest.find({ missionId }).sort({ createdAt: -1 })).map((item) => item.toJSON()); }
async function findRequest(id) { const mongoose = require("mongoose"); const { RevenueExternalActionRequest } = require("../models/RevenueExternalActionRequest"); if (!mongoose.Types.ObjectId.isValid(String(id || ""))) fail("Invalid action request id"); const item = await RevenueExternalActionRequest.findById(id); if (!item) fail("Action request not found", 404); return item; }
async function decideRequest(id, input = {}, context = {}) { const { founderApprovalGranted } = require("./revenueConversionService"); const { RevenueExternalActionDecision } = require("../models/RevenueExternalActionDecision"); if (!founderApprovalGranted(context.founderApproved)) fail("Founder approval is required for action decision", 403); const request = await findRequest(id); const previous = await RevenueExternalActionDecision.findOne({ actionRequestId: request._id }).sort({ decidedAt: -1 }); const decision = buildDecision(request, input, previous?.decisionHash); await RevenueExternalActionDecision.create(decision); request.status = decision.decision === "approved" ? "handoff_ready" : decision.decision === "request_changes" ? "changes_required" : "rejected"; request.latestDecisionHash = decision.decisionHash; request.handoffPackage = decision.decision === "approved" ? buildHandoff(request) : null; await request.save(); return { request: request.toJSON(), decision }; }
async function recordCompletion(id, input = {}, context = {}) { const { founderApprovalGranted } = require("./revenueConversionService"); if (!founderApprovalGranted(context.founderApproved)) fail("Founder approval is required to record external completion", 403); const request = await findRequest(id); request.completionReceipt = buildCompletionReceipt(request, input); request.status = "externally_completed"; await request.save(); return request.toJSON(); }
async function listDecisions(id) { const { RevenueExternalActionDecision } = require("../models/RevenueExternalActionDecision"); return (await RevenueExternalActionDecision.find({ actionRequestId: id }).sort({ decidedAt: 1 })).map((item) => item.toJSON()); }
module.exports = { assertMissionReady, buildCompletionReceipt, buildDecision, buildHandoff, buildRequest, createRequest, decideRequest, hash, listDecisions, listRequests, recordCompletion };
