/**
 * GARUDA INSTALLMENT AUTOMATION — MULTI-LANGUAGE LOCALIZATION ENGINE
 * 
 * Full Vernacular Parity Standard:
 * - English ('en')
 * - Hinglish ('hinglish' - Roman Hindi)
 * - Hindi ('hi' - Pure Devanagari Hindi)
 * 
 * Supports dynamic switching without page reload.
 */

const DICTIONARY = {
  en: {
    langCode: 'en',
    langName: 'English',
    speechLocale: 'en-IN',
    appTitle: 'GARUDA Kist',
    appSubtitle: 'Digital Installment & Ledger Book',
    today: 'Today',
    customers: 'Customers',
    customer: 'Customer',
    addCustomer: 'Add Customer',
    ledger: 'Ledger',
    settings: 'Settings',
    paymentReceived: 'Payment Received',
    received: 'Received',
    installment: 'Installment',
    pending: 'Pending',
    dueToday: 'Due Today',
    dueTomorrow: 'Due Tomorrow',
    overdue: 'Late Payment',
    history: 'Payment History',
    receipt: 'Receipt',
    search: 'Search Customer...',
    save: 'Save',
    cancel: 'Cancel',
    remaining: 'Remaining Balance',
    total: 'Total',
    paid: 'Paid',
    amountDue: 'Amount Due',
    todayCollection: "Today's Collection",
    myCustomers: 'My Customers',
    customersDueToday: 'Customers Due Today',
    tomorrowCollection: "Tomorrow's Collection",
    weeklyCollection: 'Weekly Collection',
    lateCustomers: 'customers late',
    recentPayments: 'Recent Transactions',
    allCustomers: 'All Customers',
    addByPhoto: 'Photo to Record',
    addByVoice: 'Voice Payment',
    photoToRecord: 'Photo to Record',
    voicePayment: 'Voice Payment',
    capabilities: 'More Features',
    addFeature: 'Add Feature',
    customerName: 'Customer Name',
    phoneNumber: 'Mobile Number',
    itemDescription: 'Item Description',
    totalAmount: 'Total Amount',
    downPayment: 'Down Payment',
    installmentAmount: 'Installment Amount',
    frequency: 'Payment Frequency',
    weekly: 'Weekly',
    daily: 'Daily',
    monthly: 'Monthly',
    startDate: 'Start Date',
    confirmPaymentTitle: 'Payment Received',
    confirmPaymentBtn: 'Confirm Payment',
    paymentSuccess: (name, amount) => `₹${amount} received from ${name}`,
    remainingBalanceText: (rem) => `Remaining Balance: ₹${typeof rem === 'number' ? rem.toLocaleString('en-IN') : rem}`,
    ocrTitle: 'Photo to Record',
    ocrPrompt: "Take a photo of the customer's notebook page.",
    ocrReading: 'AI reading notebook... please wait...',
    ocrVerifyBtn: 'Verify Details & Save',
    voiceTitle: 'Voice Payment',
    voicePrompt: 'Tap the microphone and speak.',
    voiceExample: 'Example: "Ramesh paid 500"',
    voiceListening: 'Listening... speak now...',
    cloudSyncStatus: 'Saved on device',
    cloudSynced: 'Cloud Synced',
    syncNow: 'Cloud Backup Now',
    printBtn: 'Print Receipt',
    shareWhatsappBtn: 'Send via WhatsApp',
    receiptModalTitle: 'Receipt & Print',
    capModalTitle: '✨ GARUDA — Expand Features',
    capModalSub: 'Modular business add-ons available for store expansion:',
    voiceExtracted: 'Extracted Details:',
    ocrCameraBtn: 'Open Camera / Scan Notebook',
    paymentMode: 'Payment Mode:',
    modeCash: '💵 Cash',
    modeUpi: '📱 UPI (PhonePe / GPay / Paytm)',
    modeBank: '🏦 Bank Transfer / Cheque',
    deviceLicense: 'Device License',
    cloudSubscription: 'Cloud Subscription',
    allDuesCollected: 'All dues for today collected!',
    invalidAmountAlert: 'Please enter a valid amount',
    requiredFieldsAlert: 'Please fill required fields',
    greeting: (name) => `Hello ${name},`,
    deviceStatusLabel: 'Device Status',
    authorizedDemo: 'Authorized Demo Device',
    subscriptionStatusLabel: 'Cloud Backup & Maintenance',
    annualFeeLabel: 'Annual Fee',
    daysRemainingLabel: 'Days Remaining',
    dataSecurityPolicy: 'Data Security: Even if your subscription expires, all your historical data is 100% safe and will never be deleted.'
  },

  hinglish: {
    langCode: 'hinglish',
    langName: 'Hinglish',
    speechLocale: 'hi-IN',
    appTitle: 'GARUDA Kist',
    appSubtitle: 'Dukandaar Ka Digital Hisaab',
    today: 'Aaj',
    customers: 'Customers',
    customer: 'Customer',
    addCustomer: 'Customer Jodein',
    ledger: 'Hisaab',
    settings: 'Settings',
    paymentReceived: 'Paisa Mila',
    received: 'Jama',
    installment: 'Kist',
    pending: 'Baaki',
    dueToday: 'Aaj Due',
    dueTomorrow: 'Kal Due',
    overdue: 'Late Payment',
    history: 'Payment History',
    receipt: 'Receipt',
    search: 'Search Customer...',
    save: 'Save Karein',
    cancel: 'Cancel',
    remaining: 'Baaki Amount',
    total: 'Total',
    paid: 'Jama',
    amountDue: 'Aaj Kitna Lena Hai',
    todayCollection: 'Aaj Ka Collection',
    myCustomers: 'Mere Customers',
    customersDueToday: 'Customers Se Lena Hai',
    tomorrowCollection: 'Kal Kitna Lena Hai',
    weeklyCollection: 'Is Week Ka Collection',
    lateCustomers: 'customers late hain',
    recentPayments: 'Recent Payments',
    allCustomers: 'Sabhi Customers',
    addByPhoto: 'Photo se Add Karein',
    addByVoice: 'Bolkar Add Karein',
    photoToRecord: 'Photo se Hisaab Add',
    voicePayment: 'Bolkar Payment',
    capabilities: 'More Features',
    addFeature: 'Feature Add Karein',
    customerName: 'Customer Ka Naam',
    phoneNumber: 'Mobile Number',
    itemDescription: 'Saaman Ka Vivaran',
    totalAmount: 'Total Price',
    downPayment: 'Down Payment (Advance)',
    installmentAmount: 'Kist Ki Rakam',
    frequency: 'Kist Kab Deni Hai?',
    weekly: 'Har Hafte (Weekly)',
    daily: 'Har Din (Daily)',
    monthly: 'Har Mahine (Monthly)',
    startDate: 'Start Date',
    confirmPaymentTitle: 'Paisa Mila',
    confirmPaymentBtn: 'Payment Confirm Karein',
    paymentSuccess: (name, amount) => `${name} se ₹${amount} mil gaye`,
    remainingBalanceText: (rem) => `Baaki: ₹${typeof rem === 'number' ? rem.toLocaleString('en-IN') : rem}`,
    ocrTitle: 'Photo se Hisaab Add Karein',
    ocrPrompt: 'Customer ki notebook ka photo lein.',
    ocrReading: 'AI diary padh raha hai... thoda wait karein...',
    ocrVerifyBtn: 'Details Sahi Hai — Save Karein',
    voiceTitle: 'Bolkar Payment',
    voicePrompt: 'Mic dabaiye aur boliye.',
    voiceExample: 'Example: "Ramesh ne 500 diye"',
    voiceListening: 'Sun raha hoon... boliye...',
    cloudSyncStatus: 'Device me Surakshit',
    cloudSynced: 'Cloud me Synced',
    syncNow: 'Cloud Backup Abhi Karein',
    printBtn: 'Receipt Print Karein',
    shareWhatsappBtn: 'WhatsApp Bhejein',
    receiptModalTitle: 'Receipt Aur Print',
    capModalTitle: '✨ GARUDA — More Features',
    capModalSub: 'Dukaan ke vistaar ke liye zaroori modules:',
    voiceExtracted: 'Samajh Aayi Details:',
    ocrCameraBtn: 'Camera Chalu Karein',
    paymentMode: 'Payment Mode:',
    modeCash: '💵 Cash (Naqd)',
    modeUpi: '📱 UPI (PhonePe / GPay / Paytm)',
    modeBank: '🏦 Bank Transfer / Cheque',
    deviceLicense: 'Device License',
    cloudSubscription: 'Cloud Subscription',
    allDuesCollected: 'Aaj ki sabhi kistein jama ho chuki hain!',
    invalidAmountAlert: 'Kripya sahi amount dalein!',
    requiredFieldsAlert: 'Kripya zaroori details bharein!',
    greeting: (name) => `Namaste ${name} ji,`,
    deviceStatusLabel: 'Device Status',
    authorizedDemo: 'Authorized Demo Device',
    subscriptionStatusLabel: 'Cloud Backup aur Maintenance',
    annualFeeLabel: 'Annual Fee',
    daysRemainingLabel: 'Days Remaining',
    dataSecurityPolicy: 'Data Safety: Subscription khatam hone par bhi aapka purana hisaab 100% surakshit rehta hai aur kabhi delete nahi hota.'
  },

  hi: {
    langCode: 'hi',
    langName: 'हिन्दी',
    speechLocale: 'hi-IN',
    appTitle: 'GARUDA Kist',
    appSubtitle: 'दुकानदार का डिजिटल हिसाब',
    today: 'आज',
    customers: 'ग्राहक',
    customer: 'ग्राहक',
    addCustomer: 'ग्राहक जोड़ें',
    ledger: 'हिसाब',
    settings: 'सेटिंग्स',
    paymentReceived: 'पैसा मिला',
    received: 'जमा',
    installment: 'किस्त',
    pending: 'बाकी',
    dueToday: 'आज देना है',
    dueTomorrow: 'कल देना है',
    overdue: 'बकाया',
    history: 'इतिहास',
    receipt: 'रसीद',
    search: 'ग्राहक खोजें...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    remaining: 'बाकी राशि',
    total: 'कुल',
    paid: 'जमा',
    amountDue: 'देय राशि',
    todayCollection: 'आज का कलेक्शन',
    myCustomers: 'मेरे ग्राहक',
    customersDueToday: 'ग्राहकों से लेना है',
    tomorrowCollection: 'कल आना है',
    weeklyCollection: 'इस हफ्ते का कलेक्शन',
    lateCustomers: 'ग्राहक लेट हैं',
    recentPayments: 'हाल के लेनदेन',
    allCustomers: 'सभी ग्राहक',
    addByPhoto: 'फोटो से जोड़ें',
    addByVoice: 'बोलकर जोड़ें',
    photoToRecord: 'फोटो से हिसाब जोड़ें',
    voicePayment: 'बोलकर भुगतान',
    capabilities: 'और फीचर्स',
    addFeature: 'फीचर जोड़ें',
    customerName: 'ग्राहक का नाम',
    phoneNumber: 'मोबाइल नंबर',
    itemDescription: 'सामान का विवरण',
    totalAmount: 'कुल कीमत',
    downPayment: 'डाउन पेमेंट (नकद जमा)',
    installmentAmount: 'किस्त की राशि',
    frequency: 'किस्त कब देनी है?',
    weekly: 'हर हफ्ते (साप्ताहिक)',
    daily: 'हर दिन (दैनिक)',
    monthly: 'हर महीने (मासिक)',
    startDate: 'शुरू करने की तारीख',
    confirmPaymentTitle: 'पैसा मिला',
    confirmPaymentBtn: 'भुगतान की पुष्टि करें',
    paymentSuccess: (name, amount) => `${name} से ₹${amount} प्राप्त हुए`,
    remainingBalanceText: (rem) => `बाकी राशि: ₹${typeof rem === 'number' ? rem.toLocaleString('en-IN') : rem}`,
    ocrTitle: 'फोटो से हिसाब जोड़ें',
    ocrPrompt: 'ग्राहक की डायरी का फोटो लें।',
    ocrReading: 'AI डायरी पढ़ रहा है... कृपया प्रतीक्षा करें...',
    ocrVerifyBtn: 'जानकारी सही है — सहेजें',
    voiceTitle: 'बोलकर भुगतान',
    voicePrompt: 'माइक दबाकर बोलें।',
    voiceExample: 'उदा. "रमेश ने 500 दिए"',
    voiceListening: 'सुन रहा हूँ... बोलिए...',
    cloudSyncStatus: 'डिवाइस में सुरक्षित',
    cloudSynced: 'क्लाउड में सिंक हुआ',
    syncNow: 'अभी क्लाउड बैकअप करें',
    printBtn: 'रसीद प्रिंट करें',
    shareWhatsappBtn: 'WhatsApp भेजें',
    receiptModalTitle: 'रसीद व प्रिंट',
    capModalTitle: '✨ GARUDA — और फीचर्स जोड़ें',
    capModalSub: 'दुकान के विस्तार के लिए आवश्यक मॉड्यूल्स:',
    voiceExtracted: 'निकाली गई जानकारी:',
    ocrCameraBtn: 'कैमरा चालू करें',
    paymentMode: 'माध्यम:',
    modeCash: '💵 नकद (Cash)',
    modeUpi: '📱 UPI (PhonePe / GPay / Paytm)',
    modeBank: '🏦 बैंक ट्रांसफर / चेक',
    deviceLicense: 'डिवाइस लाइसेंस',
    cloudSubscription: 'क्लाउड सब्सक्रिप्शन',
    allDuesCollected: 'आज की सभी किस्तें जमा हो चुकी हैं!',
    invalidAmountAlert: 'कृपया सही राशि दर्ज करें!',
    requiredFieldsAlert: 'कृपया सभी जरूरी जानकारी भरें!',
    greeting: (name) => `नमस्ते ${name} जी,`,
    deviceStatusLabel: 'डिवाइस स्थिति',
    authorizedDemo: 'अधिकृत डेमो डिवाइस',
    subscriptionStatusLabel: 'क्लाउड बैकअप व मेंटेनेंस',
    annualFeeLabel: 'वार्षिक शुल्क',
    daysRemainingLabel: 'शेष दिन',
    dataSecurityPolicy: 'डेटा सुरक्षा नीति: सब्सक्रिप्शन समाप्त होने पर भी आपका पिछला डेटा 100% सुरक्षित रहता है और कभी डिलीट नहीं होता।'
  }
};

function getDictionary(lang = 'hi') {
  return DICTIONARY[lang] || DICTIONARY.hi;
}

function translate(key, lang = 'hi', ...args) {
  const dict = getDictionary(lang);
  const val = dict[key];
  if (typeof val === 'function') return val(...args);
  return val || key;
}

module.exports = {
  DICTIONARY,
  getDictionary,
  translate
};
