const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { ProductionBatchLifecycle } = require("./ProductionBatchLifecycle");
const root = fs.mkdtempSync(path.join(os.tmpdir(), "garuda-lifecycle-"));
const lifecycle = new ProductionBatchLifecycle({ rootDir: root });
const written = lifecycle.writeCheckpoint({ batchTitle: "Integrity batch", completedWork: ["Validated evidence"], changedFiles: ["src/service.js"], executedTests: ["node test.js"], buildStatus: "PASS", packagePath: "C:/patch.zip", nextRecommendedTask: "Review patch" });
assert.ok(fs.existsSync(written.file));
const resume = lifecycle.resume();
assert.strictEqual(resume.status, "RESUME_READY");
assert.strictEqual(resume.skippedAudit, true);
assert.strictEqual(resume.checkpoint.batchTitle, "Integrity batch");
assert.match(lifecycle.generateReport(resume.checkpoint), /Await Founder approval/);
fs.writeFileSync(path.join(root, "reports", "engineering-checkpoints", "latest.json"), "{bad");
assert.strictEqual(lifecycle.resume().status, "NO_VALID_CHECKPOINT");
const environment = lifecycle.validateEnvironment();
assert.ok(environment.tools.git);
assert.strictEqual(environment.governance.networkAuthenticationNotTested, true);
console.log("Production batch lifecycle checkpoint, resume, report, and environment validation passed.");
