const discoveryService = require("../services/opportunityDiscoveryService");
const executionMissionService = require("../services/revenueExecutionMissionService");
const missionOrchestrator = require("../services/revenueMissionOrchestratorService");
const missionDecisionService = require("../services/revenueMissionDecisionService");
const deliverableWorkspaceService = require("../services/revenueDeliverableWorkspaceService");
const autonomousTaskRunner = require("../services/autonomousRevenueTaskRunnerService");
const externalActionService = require("../services/revenueExternalActionService");
const mvpReadinessService = require("../services/revenueMvpReadinessService");

function sendError(res, error, fallback) { return res.status(error.statusCode || 500).json({ success: false, message: error.message || fallback }); }
exports.list = async (req, res) => { try { return res.json({ success: true, data: await discoveryService.listCandidates(req.query || {}) }); } catch (error) { return sendError(res, error, "Failed to list discovery candidates"); } };
exports.run = async (_req, res) => { try { return res.json({ success: true, data: await discoveryService.runDiscoveryCycle() }); } catch (error) { return sendError(res, error, "Failed to run discovery cycle"); } };
exports.decide = async (req, res) => { try { return res.json({ success: true, data: await discoveryService.decideCandidate(req.params.id, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to update candidate decision"); } };
exports.createExecutionMission = async (req, res) => { try { return res.status(201).json({ success: true, data: await executionMissionService.createFromApprovedCandidate(req.params.id, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to create execution mission"); } };
exports.listExecutionMissions = async (req, res) => { try { return res.json({ success: true, data: await executionMissionService.listMissions(req.query || {}) }); } catch (error) { return sendError(res, error, "Failed to list execution missions"); } };
exports.prepareExecutionMission = async (req, res) => { try { return res.json({ success: true, data: await missionOrchestrator.prepareMission(req.params.id, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to prepare execution mission"); } };
exports.decideExecutionMission = async (req, res) => { try { return res.json({ success: true, data: await missionDecisionService.decideMission(req.params.id, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to decide execution mission"); } };
exports.listExecutionMissionDecisions = async (req, res) => { try { return res.json({ success: true, data: await missionDecisionService.listDecisions(req.params.id) }); } catch (error) { return sendError(res, error, "Failed to list mission decisions"); } };
exports.resubmitExecutionMission = async (req, res) => { try { return res.json({ success: true, data: await missionOrchestrator.resubmitMission(req.params.id, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to resubmit corrected execution mission"); } };
exports.transitionExecutionTask = async (req, res) => { try { return res.json({ success: true, data: await deliverableWorkspaceService.transitionTask(req.params.id, req.params.taskId, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to update execution task"); } };
exports.listExecutionTaskEvents = async (req, res) => { try { return res.json({ success: true, data: await deliverableWorkspaceService.listTaskEvents(req.params.id) }); } catch (error) { return sendError(res, error, "Failed to list execution task events"); } };
exports.runExecutionTask = async (req, res) => { try { return res.json({ success: true, data: await autonomousTaskRunner.runMission(req.params.id, { maxAttempts: req.body?.maxAttempts, founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to run autonomous execution task"); } };
exports.listExecutionTaskRuns = async (req, res) => { try { return res.json({ success: true, data: await autonomousTaskRunner.listRuns(req.params.id) }); } catch (error) { return sendError(res, error, "Failed to list autonomous task runs"); } };
exports.createExternalActionRequest = async (req, res) => { try { return res.status(201).json({ success: true, data: await externalActionService.createRequest(req.params.id, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to create external action request"); } };
exports.listExternalActionRequests = async (req, res) => { try { return res.json({ success: true, data: await externalActionService.listRequests(req.params.id) }); } catch (error) { return sendError(res, error, "Failed to list external action requests"); } };
exports.decideExternalActionRequest = async (req, res) => { try { return res.json({ success: true, data: await externalActionService.decideRequest(req.params.requestId, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to decide external action request"); } };
exports.listExternalActionDecisions = async (req, res) => { try { return res.json({ success: true, data: await externalActionService.listDecisions(req.params.requestId) }); } catch (error) { return sendError(res, error, "Failed to list external action decisions"); } };
exports.recordExternalActionCompletion = async (req, res) => { try { return res.json({ success: true, data: await externalActionService.recordCompletion(req.params.requestId, req.body || {}, { founderApproved: req.get("x-garuda-founder-approved") }) }); } catch (error) { return sendError(res, error, "Failed to record external action completion"); } };
exports.getMvpReadiness = async (req, res) => { try { return res.json({ success: true, data: await mvpReadinessService.getReadiness(req.params.id) }); } catch (error) { return sendError(res, error, "Failed to assess revenue MVP readiness"); } };
