/**
 * GARUDA Social Engine - Worker State Machine
 * Principle 1 & 3: Strict state verification, zero invalid state transitions.
 */

const WORKER_STATES = Object.freeze({
  IDLE: 'IDLE',
  INITIALIZING: 'INITIALIZING',
  ACQUIRING_LOCK: 'ACQUIRING_LOCK',
  STARTING_BROWSER: 'STARTING_BROWSER',
  LAUNCHING_BROWSER: 'LAUNCHING_BROWSER',
  CONNECTING: 'CONNECTING',
  ATTACHING_BROWSER: 'ATTACHING_BROWSER',
  AUTH_CHECK: 'AUTH_CHECK',
  READY: 'READY',
  NAVIGATING: 'NAVIGATING',
  DISCOVERING: 'DISCOVERING',
  EXTRACTING: 'EXTRACTING',
  NORMALIZING: 'NORMALIZING',
  QUALIFYING: 'QUALIFYING',
  VALIDATING: 'VALIDATING',
  QUEUED: 'QUEUED',
  AWAITING_APPROVAL: 'AWAITING_APPROVAL',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  OUTREACHING: 'OUTREACHING',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  UNKNOWN: 'UNKNOWN',
  RATE_LIMITED: 'RATE_LIMITED',
  COOLDOWN: 'COOLDOWN',
  SECURITY_BLOCKED: 'SECURITY_BLOCKED',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  RETRY_WAIT: 'RETRY_WAIT',
  FAILED: 'FAILED',
  STOPPING: 'STOPPING',
  STOPPED: 'STOPPED'
});

const VALID_TRANSITIONS = new Map([
  [WORKER_STATES.INITIALIZING, [WORKER_STATES.ACQUIRING_LOCK, WORKER_STATES.STARTING_BROWSER, WORKER_STATES.LAUNCHING_BROWSER, WORKER_STATES.CONNECTING, WORKER_STATES.ATTACHING_BROWSER, WORKER_STATES.FAILED, WORKER_STATES.STOPPED]],
  [WORKER_STATES.ACQUIRING_LOCK, [WORKER_STATES.STARTING_BROWSER, WORKER_STATES.LAUNCHING_BROWSER, WORKER_STATES.ATTACHING_BROWSER, WORKER_STATES.CONNECTING, WORKER_STATES.FAILED, WORKER_STATES.COOLDOWN, WORKER_STATES.STOPPING]],
  [WORKER_STATES.STARTING_BROWSER, [WORKER_STATES.AUTH_CHECK, WORKER_STATES.NAVIGATING, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.LAUNCHING_BROWSER, [WORKER_STATES.AUTH_CHECK, WORKER_STATES.NAVIGATING, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.CONNECTING, [WORKER_STATES.AUTH_CHECK, WORKER_STATES.ATTACHING_BROWSER, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.ATTACHING_BROWSER, [WORKER_STATES.AUTH_CHECK, WORKER_STATES.NAVIGATING, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.AUTH_CHECK, [WORKER_STATES.READY, WORKER_STATES.AUTH_EXPIRED, WORKER_STATES.SECURITY_BLOCKED, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.READY, [WORKER_STATES.DISCOVERING, WORKER_STATES.NAVIGATING, WORKER_STATES.IDLE, WORKER_STATES.RATE_LIMITED, WORKER_STATES.COOLDOWN, WORKER_STATES.STOPPING, WORKER_STATES.SECURITY_BLOCKED]],
  [WORKER_STATES.NAVIGATING, [WORKER_STATES.DISCOVERING, WORKER_STATES.EXTRACTING, WORKER_STATES.SECURITY_BLOCKED, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.DISCOVERING, [WORKER_STATES.EXTRACTING, WORKER_STATES.IDLE, WORKER_STATES.SECURITY_BLOCKED, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.EXTRACTING, [WORKER_STATES.NORMALIZING, WORKER_STATES.VALIDATING, WORKER_STATES.UNKNOWN, WORKER_STATES.SECURITY_BLOCKED, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.NORMALIZING, [WORKER_STATES.QUALIFYING, WORKER_STATES.VALIDATING, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.QUALIFYING, [WORKER_STATES.QUEUED, WORKER_STATES.IDLE, WORKER_STATES.COMPLETED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.VALIDATING, [WORKER_STATES.QUEUED, WORKER_STATES.IDLE, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.QUEUED, [WORKER_STATES.AWAITING_APPROVAL, WORKER_STATES.WAITING_APPROVAL, WORKER_STATES.OUTREACHING, WORKER_STATES.IDLE, WORKER_STATES.STOPPING]],
  [WORKER_STATES.AWAITING_APPROVAL, [WORKER_STATES.OUTREACHING, WORKER_STATES.IDLE, WORKER_STATES.STOPPING]],
  [WORKER_STATES.WAITING_APPROVAL, [WORKER_STATES.OUTREACHING, WORKER_STATES.IDLE, WORKER_STATES.STOPPING]],
  [WORKER_STATES.OUTREACHING, [WORKER_STATES.VERIFYING, WORKER_STATES.COMPLETED, WORKER_STATES.SECURITY_BLOCKED, WORKER_STATES.RATE_LIMITED, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.VERIFYING, [WORKER_STATES.COMPLETED, WORKER_STATES.IDLE, WORKER_STATES.FAILED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.COMPLETED, [WORKER_STATES.IDLE, WORKER_STATES.COOLDOWN, WORKER_STATES.STOPPING]],
  [WORKER_STATES.UNKNOWN, [WORKER_STATES.IDLE, WORKER_STATES.COMPLETED, WORKER_STATES.STOPPING]],
  [WORKER_STATES.IDLE, [WORKER_STATES.DISCOVERING, WORKER_STATES.NAVIGATING, WORKER_STATES.AUTH_CHECK, WORKER_STATES.COOLDOWN, WORKER_STATES.STOPPING]],
  [WORKER_STATES.RATE_LIMITED, [WORKER_STATES.COOLDOWN, WORKER_STATES.IDLE, WORKER_STATES.STOPPING]],
  [WORKER_STATES.COOLDOWN, [WORKER_STATES.IDLE, WORKER_STATES.READY, WORKER_STATES.STOPPING]],
  [WORKER_STATES.SECURITY_BLOCKED, [WORKER_STATES.STOPPING, WORKER_STATES.STOPPED]],
  [WORKER_STATES.AUTH_EXPIRED, [WORKER_STATES.STOPPING, WORKER_STATES.STOPPED, WORKER_STATES.AUTH_CHECK]],
  [WORKER_STATES.RETRY_WAIT, [WORKER_STATES.INITIALIZING, WORKER_STATES.ACQUIRING_LOCK, WORKER_STATES.STOPPING, WORKER_STATES.STOPPED]],
  [WORKER_STATES.FAILED, [WORKER_STATES.RETRY_WAIT, WORKER_STATES.INITIALIZING, WORKER_STATES.STOPPING, WORKER_STATES.STOPPED]],
  [WORKER_STATES.STOPPING, [WORKER_STATES.STOPPED]],
  [WORKER_STATES.STOPPED, [WORKER_STATES.INITIALIZING]]
]);

class WorkerStateMachine {
  constructor(platform, initialListener = null) {
    this.platform = platform;
    this.currentState = WORKER_STATES.INITIALIZING;
    this.history = [{ state: this.currentState, timestamp: new Date().toISOString(), reason: 'Initial startup' }];
    this.listeners = initialListener ? [initialListener] : [];
  }

  getState() {
    return this.currentState;
  }

  canTransitionTo(nextState) {
    const allowed = VALID_TRANSITIONS.get(this.currentState) || [];
    return allowed.includes(nextState);
  }

  transition(nextState, reason = '') {
    if (this.currentState === nextState) return this.currentState;

    const allowed = VALID_TRANSITIONS.get(this.currentState) || [];
    if (!allowed.includes(nextState)) {
      const err = new Error(`[StateMachine:${this.platform}] Invalid state transition: ${this.currentState} -> ${nextState}. Reason: ${reason}`);
      err.name = 'InvalidStateTransitionError';
      throw err;
    }

    const previousState = this.currentState;
    this.currentState = nextState;
    const transitionRecord = {
      from: previousState,
      to: nextState,
      timestamp: new Date().toISOString(),
      reason
    };
    this.history.push(transitionRecord);
    if (this.history.length > 50) this.history.shift();

    for (const listener of this.listeners) {
      try {
        listener(transitionRecord);
      } catch (err) {
        console.error(`[StateMachine:${this.platform}] Listener callback error:`, err.message);
      }
    }

    return this.currentState;
  }

  onTransition(callback) {
    this.listeners.push(callback);
  }
}

module.exports = {
  WORKER_STATES,
  VALID_TRANSITIONS,
  WorkerStateMachine
};
