const fs = require("fs");
fs.mkdirSync("public", { recursive: true });

fs.writeFileSync("public/index.html", `<!DOCTYPE html><html><head><title>GARUDA AI</title><link rel="stylesheet" href="/style.css"></head><body><div class="sky"></div><main class="portal"><div class="bird">??</div><div class="badge">India's Personal AI Operating System</div><h1>GARUDA</h1><p>One Command. Infinite Intelligence.</p><div class="cards"><span>Mother Core</span><span>Insurance AI</span><span>Companion</span></div><a class="enter" href="/app.html">Enter GARUDA</a></main></body></html>`);

fs.writeFileSync("public/app.html", `<!DOCTYPE html><html><head><title>GARUDA Console</title><link rel="stylesheet" href="/style.css"></head><body><main class="shell"><aside><h2>GARUDA</h2><p>Mother Core Online</p><nav><b>Companion</b><b>Knowledge</b><b>Insurance</b><b>Mother Core</b></nav></aside><section class="panel"><div class="top"><div><h1>Welcome, Founder</h1><p>Ask GARUDA anything from knowledge base.</p></div><div class="status">? Mongo + RAG Active</div></div><div id="chat" class="chat"><div class="msg ai">Namaste Founder. GARUDA ready hai.</div></div><form id="form"><input id="q" placeholder="Ask GARUDA..." autocomplete="off"><button>Ask</button></form></section></main><script src="/app.js"></script></body></html>`);

fs.writeFileSync("public/app.js", `const chat=document.getElementById("chat"),form=document.getElementById("form"),q=document.getElementById("q");form.onsubmit=async e=>{e.preventDefault();const text=q.value.trim();if(!text)return;chat.innerHTML+=\`<div class="msg user">\${text}</div>\`;q.value="";chat.innerHTML+=\`<div class="msg ai" id="loading">Thinking...</div>\`;try{let r=await fetch("/api/rag?q="+encodeURIComponent(text));let d=await r.json();document.getElementById("loading").remove();chat.innerHTML+=\`<div class="msg ai">\${d.answer||d.response||d.message||JSON.stringify(d)}</div>\`;}catch(err){document.getElementById("loading").remove();chat.innerHTML+=\`<div class="msg ai">Backend se response nahi mila.</div>\`;}}`);

fs.writeFileSync("public/style.css", `*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial;background:#030711;color:white;overflow:hidden}.sky{position:fixed;inset:0;background:radial-gradient(circle at 50% 20%,#1b7b64 0,#07111f 38%,#02040a 80%)}.portal{height:100vh;display:grid;place-content:center;text-align:center;position:relative}.bird{font-size:76px;animation:float 3s infinite ease-in-out}.badge{margin:auto;padding:10px 20px;border:1px solid #d6b55d;border-radius:999px;color:#ffe28a;background:#ffffff10;width:max-content}h1{font-size:96px;letter-spacing:16px;margin:22px 0 8px;text-shadow:0 0 40px #77ffe0}p{color:#cfe8ef;font-size:20px}.cards{display:flex;gap:16px;justify-content:center;margin:28px}.cards span,.status{padding:14px 18px;border:1px solid #2d4258;border-radius:18px;background:#081426cc}.enter,button{background:#ffe26b;color:#07111f;border:0;border-radius:16px;padding:15px 24px;font-weight:800;text-decoration:none}.shell{display:flex;height:100vh;background:radial-gradient(circle at top,#102b34,#030711 70%)}aside{width:280px;padding:34px;border-right:1px solid #1d3345;background:#050b14cc}aside h2{letter-spacing:5px}nav{display:grid;gap:14px;margin-top:45px}nav b{padding:15px;border-radius:14px;background:#0d1825}.panel{flex:1;padding:45px;display:flex;flex-direction:column}.top{display:flex;justify-content:space-between;align-items:center}.top h1{font-size:58px;letter-spacing:4px}.chat{flex:1;margin:25px 0;padding:20px;border:1px solid #20384d;border-radius:24px;background:#07101dcc;overflow:auto}.msg{max-width:75%;padding:15px 18px;margin:12px;border-radius:18px}.ai{background:#0f2133}.user{background:#ffe26b;color:#08111d;margin-left:auto}form{display:flex;gap:12px}input{flex:1;padding:18px;border-radius:16px;border:1px solid #2b455c;background:#07101d;color:white;font-size:16px}@keyframes float{50%{transform:translateY(-18px)}}`);

console.log("GARUDA Experience upgraded.");
