@echo off
echo Opening YouTube Studio Edit page for Sara Zamana video...
start "" "https://studio.youtube.com/video/s-uFBOXA0ME/edit"
echo Opening Local Shorts Hub...
start "" "%~dp0output\shorts\index.html"
